project:
  type: website
  output-dir: docs

website:
  title: "collab_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: more_crows.qmd
        text: More Crows

html:
    theme: lux
    css: styles.css
    toc: true
    page-layout: full



